# Generated by Django 5.1.7 on 2025-03-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_artist_music"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music",
                to="api.artist",
            ),
        ),
        migrations.AlterModelTable(
            name="artist",
            table="artists",
        ),
        migrations.AlterModelTable(
            name="music",
            table="music",
        ),
    ]
